#!/usr/bin/env bash

if ! docker image inspect crypto-test:latest &>/dev/null; then
    echo -e "=== Building Docker image...\n"
    docker build -t crypto-test .
    echo -e "\n"
fi

if [[ ! -f .credentials ]]; then
    ./set_credentials
fi

echo -e "=== Running Docker image\n"
docker run --rm -v logs:/home/test/logs --user test --env-file .credentials crypto-test
